HuangJackie/CSC404-PaintWalker

- Assets/Models/block 1.fbx
- Assets/Models/block 1.fbx.meta
- Assets/Resources/Paint_Walker_Music_-_GameJam2.wav
- Assets/Resources/Paint_Walker_Music_-_GameJam2.wav.meta
- Assets/Scenes/MovementScene.unity
- Assets/Scripts/Ground.cs
- Assets/Scripts/Player.cs
- ProjectSettings/TagManager.asset
> Player movement

- Assets/Scenes/GamePitch.unity
- Assets/Scripts/LevelManager.cs
- Assets/Scripts/PaintBucketIcon.cs
- Assets/Scripts/PaintLeftBar.cs
- Assets/Scripts/PaintLeftText.cs
- Assets/Scripts/UpdateUI.cs
- Assets/Sprites/paintBucketBlackIcon.png
- Assets/Sprites/paintBucketBlackIcon.png.meta
- Assets/Sprites/paintBucketOrangeIcon.png
- Assets/Sprites/paintBucketOrangeIcon.png.meta
- Assets/Sprites/paintBucketSpecialIcon.png
- Assets/Sprites/paintBucketSpecialIcon.png.meta
Changes icons upon paint change.
Made percentage text more realistic.
> Icon updates

- Assets/Models/fox_retopo.fbx
- Assets/Models/fox_retopo.fbx.meta
- Assets/Music.meta
- Assets/Music/sketch_for_game_jam.mp3
- Assets/Music/sketch_for_game_jam.mp3.meta
- Assets/Scenes/GamePitch.unity
- Assets/Scripts/Ground.cs
- Assets/Scripts/LevelManager.cs
- Assets/Scripts/paint types.meta
- Assets/Scripts/paint types/pushableBlock.cs
- Assets/Scripts/paint types/pushableBlock.cs.meta
Current colours for the effects are just for testing purposes. 
Cyan block can be pushed after coloured,
red is just the black drop effect inverted.
> Moveable block(cyan) and rising block(red)

- Assets/Materials/Special.mat
- Assets/Scenes/GamePitch.unity
- Assets/Scripts/Ground.cs
- Assets/Scripts/LevelManager.cs
- Assets/Scripts/PaintBucketIcon.cs
- Assets/Scripts/Paints.cs
- Assets/Scripts/RammingSpecialCreature.cs
- Assets/Scripts/RammingSpecialCreature.cs.meta
- Assets/Scripts/UpdateUI.cs
- ProjectSettings/TagManager.asset
See team tech channel for details
> various bug fixes and paint color function change

- Assets/Scripts/Creatures/RammingCreature.cs
- Assets/Scripts/LevelManager.cs
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/UI/PaintBucketIcon.cs
- Assets/Scripts/UI/PaintLeftBar.cs
List of changes/bug fixes:
1. removed exit pressure pad for main level, door is active by default
2. fixed activating ramming creature with player in the way sends the camera to oblivion
3. fixed all bugs affecting the existing UI
> more UI and mechanic bug fixes

- Assets/Models/Level_Exit_Low (1).fbx
- Assets/Models/Level_Exit_Low (1).fbx.meta
- Assets/Music/Paintwalker_-_BGM_2_v.02 (2).mp3
- Assets/Music/Paintwalker_-_BGM_2_v.02 (2).mp3.meta
- Assets/Scenes/TutorialColors.unity
Still missing textures.
https://github.com/HuangJackie/CSC404-PaintWalker/issues/89
> fix shadows, update music for tut, added door model 

- Assets/Prefabs/ControllerSystem.prefab
- Assets/Prefabs/ControllerSystem.prefab.meta
- Assets/Prefabs/PaintingSystem.prefab
- Assets/Prefabs/PaintingSystem.prefab.meta
- Assets/Scenes/TutorialColors.unity
- Assets/Scripts/Interactable.cs
- ProjectSettings/InputManager.asset
- Add more guidance in post signs
- Fix unity console errors
> Tutorial fixes

- Assets/Scripts/Creatures/SpecialCreature.cs
- Assets/Scripts/Environment/Ground.cs
- Assets/Scripts/Environment/Paintable.cs
- Assets/Scripts/Player/PaintingSystem.cs
- Assets/Scripts/Player/Player.cs
Adds a boolean flag to the (paintable) ground/special creature script called IsPaintable. By default this is set to true.
> Add unpaintable flag on the paintable script

- Assets/Scripts/Camera/ChangePerspective.cs
- Assets/Scripts/GameConstants.cs
- Assets/Scripts/Player/Player.cs
- Change camera rotation to 90 degrees
- Give isometric camera a direction = N, E, S, or W
- Adjust player movement and model according to the direction the camera is facing
> Camera Rotation 90 Degrees

- Assets/Scripts/Camera/ChangePerspective.cs
- Assets/Scripts/GameConstants.cs
- Assets/Scripts/Player/Player.cs
Reverts HuangJackie/CSC404-PaintWalker#143
> Revert "Camera Rotation 90 Degrees"

- Assets/Scripts/Camera/ChangePerspective.cs
- Assets/Scripts/GameConstants.cs
- Assets/Scripts/Player/Player.cs
Reverts HuangJackie/CSC404-PaintWalker#144
> Revert "Revert "Camera Rotation 90 Degrees""

- Assets/Materials/Player/PaintBottle/Paint.mat
- Assets/Materials/Player/PaintBrush/Tip.mat
- Assets/Prefabs/UI/HUD.prefab
- Assets/Scenes/Level1.unity
- Assets/Scripts/Environment/PaintOrb.cs
- Assets/Scripts/Managers/ControllerUtil.cs
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/UI/DisplayCheckpointHint.cs
- Assets/Scripts/UI/DisplayCheckpointHint.cs.meta
- Assets/Scripts/UI/Menus/PauseMenu.cs
- Assets/Scripts/UI/UpdateUI.cs
- Assets/Sprites/UI/Checkpoint Hint.png
- Assets/Sprites/UI/Checkpoint Hint.png.meta
- Assets/Sprites/UI/UpdatedControls.jpg
- Assets/Sprites/UI/UpdatedControls.jpg.meta
- ProjectSettings/InputManager.asset
Still needs animation for the text.
> Restart controller support

- Assets/Materials/Player/PaintBottle/Paint.mat
- Assets/Materials/Player/PaintBrush/Tip.mat
- Assets/Prefabs/Camera.meta
- Assets/Prefabs/Camera/WorldPivot.prefab
- Assets/Prefabs/Camera/WorldPivot.prefab.meta
- Assets/Scenes/Level1.unity
- Assets/Scenes/Tutorial1.unity
- Assets/Scenes/Tutorial15.unity
- Assets/Scenes/Tutorial2.unity
- Assets/Scripts/Camera/CameraRotation.cs
fixed camera not rotating around the player
> fixed camera not rotating around the player

- Assets/Prefabs/Managers/AmbienceSoundManager.prefab
- Assets/Prefabs/Managers/AmbienceSoundManager.prefab.meta
- Assets/Prefabs/Managers/BackgroundMusicManager.prefab
- Assets/Prefabs/Managers/BackgroundMusicManager.prefab.meta
- Assets/Scenes/Level1.unity
- Assets/Scenes/Tutorial1.unity
- Assets/Scenes/Tutorial15.unity
- Assets/Scenes/Tutorial2.unity
- Assets/Scripts/Managers/AmbienceSoundManager.cs
- Assets/Scripts/Managers/AmbienceSoundManager.cs.meta
- Assets/Scripts/Managers/BackgroundMusicManager.cs
- Assets/Scripts/Managers/BackgroundMusicManager.cs.meta
- Assets/Sounds/Blocks/Yellow.meta
- Assets/Sounds/Blocks/Yellow/sfx_YellowBlockPaint_v3.wav
- Assets/Sounds/Blocks/Yellow/sfx_YellowBlockPaint_v3.wav.meta
- added ambience and music managers (objects + scripts)
- moved audio source components from scene cameras to manager objects
- created prefabs for ambience and music managers
- managers added to Level1, Tutorial1, tutorial2, and Tutorial15
- added sfx_YellowBlockPaint & replaced Yellow block audio source clips
> ambience and music managers

- Assets/Scenes/Level1.unity
- Assets/Scripts/Environment/Exit.cs
- Assets/Scripts/Environment/Ground.cs
- Assets/Scripts/Managers/SceneLoader.cs
- Assets/Scripts/Managers/SoundManager.cs
- Assets/Scripts/Player/Player.cs
- 
- transition to next scene after a level is complete
> added exit transition to next scene

- Assets/Scripts/Environment/Ground.cs
- Assets/Scripts/Player/PaintingSystem.cs
Adding a 0.1 sec delay for yellow/red and 0.2 sec delay for blue before it moves to give the player a chance to step on the block instead of colliding into it.
> painting delay

- Assets/Materials/Player/PaintBottle/Paint.mat
- Assets/Materials/Player/PaintBrush/Tip.mat
- Assets/Prefabs/UI/ColorWheelHUD.prefab
- Assets/Scenes/AlphaScenev2.unity
- Assets/Scenes/DesignDoc.unity
- Assets/Scenes/Level1.unity
- Assets/Scenes/Tutorial1.unity
- Assets/Scenes/Tutorial15.unity
- Assets/Scenes/Tutorial2.unity
- Assets/Scenes/TutorialColors.unity
- Assets/Scripts/Creatures/HowlingCreature.cs
- Assets/Scripts/Creatures/RammingCreature.cs
- Assets/Scripts/Creatures/SpecialCreature.cs
- Assets/Scripts/Creatures/SpecialCreatureUtil.cs
- Assets/Scripts/Creatures/TpCreature.cs
- Assets/Scripts/Environment/Ground.cs
- Assets/Scripts/Environment/PaintOrb.cs
- Assets/Scripts/GameConstants.cs
- Assets/Scripts/Managers/LevelManager.cs
- Assets/Scripts/Managers/PaintSwitchManager.cs
- Assets/Scripts/Player/PaintBottle.cs
- Assets/Scripts/Player/PaintBrush.cs
- Assets/Scripts/Redo/MoveRedo.cs
- Assets/Scripts/UI/ColorWheelQuadrant.cs
- Assets/Scripts/UI/HUD/PaintBucketIcon.cs
- Assets/Scripts/UI/HUD/PaintLeftBar.cs
- Assets/Scripts/UI/UpdateUI.cs
See git messages for features/changes
Closes #155
> Level Manager features

- Assets/Music/music_BGM_Level1.wav
- Assets/Music/music_BGM_Level1.wav.meta
- Assets/Music/music_BGM_Level2.wav
- Assets/Music/music_BGM_Level2.wav.meta
- Assets/Music/music_BGM_MainMenu.wav
- Assets/Music/music_BGM_MainMenu.wav.meta
- Assets/Prefabs/Managers/BackgroundMusicManager.prefab
- Assets/Scenes/Level1.unity
- Assets/Scenes/MainMenuScene.unity
- Assets/Scripts/Audio.meta
- Assets/Scripts/Audio/MusicClipSwapLevel1.cs
- Assets/Scripts/Audio/MusicClipSwapLevel1.cs.meta
- Assets/Scripts/Audio/MusicClipSwapMainMenu.cs
- Assets/Scripts/Audio/MusicClipSwapMainMenu.cs.meta
- Assets/Sounds/sfx_MenuItemCancel.wav
- Assets/Sounds/sfx_MenuItemCancel.wav.meta
- Assets/Sounds/sfx_MenuItemConfirm.wav
- Assets/Sounds/sfx_MenuItemConfirm.wav.meta
- Assets/Sounds/sfx_MenuItemHover.wav
- Assets/Sounds/sfx_MenuItemHover.wav.meta
NEW ASSETS
music_BGM_MainMenu
music_BGM_Level1
music_BGM_Level2
sfx_MenuItemHover
sfx_MenuItemCancel
sfx_MenuItemConfirm
NEW SCRIPTS:
folder (new): Audio
- MusicClipSwapMainMenu
- MusicClipSwapLevel1
> Music mainmenu

- Assets/Materials/Player/PaintBottle/Paint.mat
- Assets/Materials/Player/PaintBrush/Tip.mat
- Assets/Music/MenuMusicMixer.mixer
- Assets/Music/MenuMusicMixer.mixer.meta
- Assets/Prefabs/UI/SceneTransitionEffect.prefab
- Assets/Scenes/Level1.unity
- Assets/Scenes/MainMenuScene.unity
- Assets/Scenes/Tutorial1.unity
- Assets/Scenes/Tutorial15.unity
- Assets/Scenes/Tutorial2.unity
- Assets/Scripts/Audio/MenuMusicFade.cs
- Assets/Scripts/Audio/MenuMusicFade.cs.meta
- Assets/Scripts/Audio/MusicClipSwapTutorial1.cs
- Assets/Scripts/Audio/MusicClipSwapTutorial1.cs.meta
- Assets/Scripts/Audio/MusicClipSwapTutorial15.cs
- Assets/Scripts/Audio/MusicClipSwapTutorial15.cs.meta
- Assets/Scripts/Audio/MusicClipSwapTutorial2.cs
- Assets/Scripts/Audio/MusicClipSwapTutorial2.cs.meta
- Assets/Scripts/Environment/PaintOrb.cs
- Assets/Scripts/UI/Menus/LevelSelectMenu.cs
- Assets/Sounds/sfx_PickupPaint.wav
- Assets/Sounds/sfx_PickupPaint.wav.meta
- fixed menu music to not persist on scene change and to fade-out upon scene selection
- added orb pickup sounds for all scenes
- applied footsteps/brushstroke sounds to tutorial scenes
> fixed menu music, added orb pickup sound, applied footsteps/brushstroke to other scenes beyond level1

- Assets/Materials/Player/PaintBottle/Paint.mat
- Assets/Materials/Player/PaintBrush/Tip.mat
- Assets/Materials/blocks/Starry.mat
- Assets/Materials/blocks/starry updated.jpg
- Assets/Materials/blocks/starry updated.jpg.meta
- Assets/Materials/blocks/starry_block.png
- Assets/Materials/blocks/starry_block.png.meta
- Assets/Materials/blocks/starry_block2.png
- Assets/Materials/blocks/starry_block2.png.meta
- Assets/Materials/blocks/starry_block_v3.png
- Assets/Materials/blocks/starry_block_v3.png.meta
- Assets/Scenes/Tutorial1.unity
- update black block texture
- fix paint orb rotation in tut 1
> Update Black block

- Assets/Scenes/Tutorial15.unity
Added the missing restart game object and linked the exit game object as the object to pan to.
> fix camera bug

- Assets/BGM.mixer
- Assets/BGM.mixer.meta
- Assets/Music/music_BGM_Level3.wav
- Assets/Music/music_BGM_Level3.wav.meta
- Assets/Music/music_FinalDoorMusic_v2.wav
- Assets/Music/music_FinalDoorMusic_v2.wav.meta
- Assets/Scenes/Level1.unity
- Assets/Scenes/Level3.unity
- Assets/Scenes/MainMenuScene.unity
- Assets/Scenes/Tutorial1.unity
- Assets/Scenes/Tutorial15.unity
- Assets/Scenes/Tutorial2.unity
- Assets/Scripts/Creatures/TpCreature.cs
- Assets/Scripts/Environment/Exit.cs
- Assets/Sounds/ambience_all_loop_v6.wav
- Assets/Sounds/ambience_all_loop_v6.wav.meta
- Assets/Sounds/sfx_Teleport.wav
- Assets/Sounds/sfx_Teleport.wav.meta
- added/implemented level 3 music
- added/implemented teleport sound for level 3 creatures
- edited TpCreature.cs
- edited Exit.cs
- added/implemented new ambience asset
- added/implemented final door/final exit music
- implemented mixer/snapshot system to fade out BGM when player completes level 1, level 3, and tutorial2
> level 3 audio, added teleport sound and other changes
